name: Build and Deploy

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: "${{ matrix.runner }}"
    name: "${{ matrix.name }}"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust ğŸ”§
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install Deps ğŸ”§
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Compile TS ğŸ”§
        run: |
          yarn ts:compile

      - name: Build App ğŸ”§
        run: |
          yarn compile

      - name: Upload Artifact (Linux)
        if: startsWith( matrix.runner, 'ubuntu' )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-${{ github.ref_name }}
          path: dist/osumemory-ts
  
      - name: Upload Artifact (Mac OS)
        if: startsWith( matrix.runner, 'macos' )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-${{ github.ref_name }}
          path: dist/osumemory-ts.app

      - name: Upload Artifact (Windows)
        if: startsWith( matrix.runner, 'windows' )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-${{ github.ref_name }}
          path: dist/osumemory-ts.exe