name: Build and Deploy

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]

    runs-on: "${{ matrix.os }}"
    name: "Build on ${{ matrix.os }}"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust ğŸ”§
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Compile Memory lib ğŸ”§
        run: |
          cd packages/tsprocess
          npm install
          npm run build

      - name: Install Deps ğŸ”§
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Compile TS ğŸ”§
        run: |
          yarn ts:compile

      - name: Build App ğŸ”§
        run: |
          yarn compile

      # - name: Upload Artifact (Linux)
      #   if: startsWith( matrix.os, 'ubuntu' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu
  
      # - name: Upload Artifact (Mac OS)
      #   if: startsWith( matrix.os, 'macos' )
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-${{ github.ref_name }}
      #     path: dist/tosu.app

      - name: Upload Artifact (Windows)
        if: startsWith( matrix.os, 'windows' )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ github.ref_name//\//_ }}
          path: dist/tosu.exe
