name: build & deploy

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
    paths:
      - ".github/workflows/**/*"
      - "packages/**/*"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - "packages/**/*"
      - "package.json"
      - "pnpm-lock.yaml"

concurrency:
  group: build-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    name: "build for ${{ matrix.os }}"
    steps:
      - name: ğŸ›ï¸ - Checkout
        uses: actions/checkout@v3

      - name: ğŸ“ - Define variables (1)
        if: github.event_name == 'pull_request'
        id: set-pr-sha
        shell: bash
        run: echo "SHORT_PR_SHA=$(git rev-parse HEAD | cut -c 1-7)" >> "$GITHUB_OUTPUT"

      - name: ğŸ› ï¸ - Install Node
        uses: actions/setup-node@v3
        with: { node-version: 20.11.1 }

      - name: ğŸ› ï¸ - Install Rust
        uses: moonrepo/setup-rust@v1
        with: {
          components: clippy,
          channel: '1.77.0'
        }

      - name: ğŸ› ï¸ - Install Deps
        run: npm install -g pnpm@^8 && pnpm install --frozen-lockfile

      - name: ğŸ“¦ - Build (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: pnpm build:win

      - name: ğŸ“¦ - Build (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm build:linux

      - name: ğŸš€ - Upload artifacts for windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with: {
          name: "tosu-windows-${{ steps.set-pr-sha.outputs.SHORT_PR_SHA || github.ref_name }}",
          path: packages/tosu/dist/tosu.exe
        }

      - name: ğŸš€ - Upload artifacts for linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with: {
          name: "tosu-linux-${{ steps.set-pr-sha.outputs.SHORT_PR_SHA || github.ref_name }}",
          path: packages/tosu/dist/tosu
        }

      # - name: ğŸš€ - Upload artifacts for mac
      #   if: matrix.os == 'macos-latest'
      #   uses: actions/upload-artifact@v3
      #   with: {
      #     name: "${{ steps.set-artifact-name.outputs.ARTIFACT_NAME }}",
      #     path: packages/tosu/dist/tosu.exe
      #   }
