name: PR-check

on:
  pull_request:

concurrency:
  group: lint-${{ github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust ğŸ”§
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install Deps ğŸ”§
        run: |
          npm install -g pnpm@^8
          pnpm install --frozen-lockfile

      - name: Lint PR
        run: |
          pnpm run prettier:ci